spring.datasource.url=${dev_db_host}
spring.datasource.username=${dev_db_username}
spring.datasource.password=${dev_db_password}
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:sql/schema.sql
spring.sql.init.data-locations=classpath:sql/data.sql